version: '2'

services:
  db:
    image: "mdillon/postgis:9.5-alpine"
    volumes_from:
      - data
    ports:
     - "5432:5432"
  data:
    image: cogniteev/echo
    command: echo 'Data Container for PostgreSQL'
    volumes:
      - /var/lib/postgresql/data
